language: haskell
ghc:
  - "9.0.2"
sudo: false
notifications:
  email: false

script:
  - cabal configure --enable-tests && cabal build && cabal test

install:
  - cabal install --only-dependencies --enable-tests --reorder-goals --max-backjumps=-1
